.View diagram
[%collapsible]
====
{{#graph}}
  "model": "secdeva/graphModels/processDiagram",
  "view": "secdeva/graphViews/processTask"
{{/graph}}
====

Security requirements define required security capabilities, required security-related features or other required security-related characteristics of the product.

== How to decide if this control is required

Security requirements specification is required, if security requirements have been identified in the project.

Typical areas for security requirements include:

- General security capabilities
- Access control, permissions, permission delegation
- Anti-tampering and integrity mechanisms
- Usage of cryptography
- Secure storage of secrets

You should create security requirements, when the requirement is non-trivial and needs to be widely reviewed.

== How to implement

1. Document the scope and boundaries of the product or system, and the required IEC 62443 security capability level in the security requirement register {{#report}}"name": "secdeva/reports/xref", "identifier":"secdeva_register_security-requirements"{{/report}}.

2. Create individual security requirements in the security requirement register {{#report}}"name": "secdeva/reports/xref", "identifier":"secdeva_register_security-requirements"{{/report}}. Each security requirement includes review subtasks for 4 different roles. Write the description of the requirements and complete the reviews.

3. Conduct a review of security requirement management to ensure that all relevant requirements have been identified.

{{#report}}
  "name": "secdeva/reports/createReview",
  "template": "secdeva/templates/requirementManagementReview",
  "buttonLabel": "Create a review of security requirement management",
  "phase": "secdeva_phase_design"
{{/report}}

== Assessment

{{#report}}
  "name": "secdeva/reports/internalControlAssessment"
{{/report}}

== References

* IEC 62443-4-1 SR-3
* IEC 62443-4-1 SR-4
* IEC 62443-4-1 SR-5
* ISO 27001 A8.26
* EU CRA Article 13 (3)
* EU CRA Article 13 (4)
* EU CRA Article 31 (1)
* EU CRA Annex I (1) (1)