== Introduction

Threat modelling is a process to identify security threats based on the projected product architecture. This threat model covers the scope of development project.

== Assets

Assets are documented as part of the threat model and, if necessary, separately in the asset register, see {{#report}}"name": "secdeva/reports/xref", "identifier": "secdeva_register_assets"{{/report}}.

{{#report}}
  "name": "secdeva/reports/assets"
{{/report}}

== Security context

Security context must be documented before a threat model can be approved.

{{#report}}
  "name": "secdeva/reports/linkByIdentifier",
  "identifier": "secdeva_document_security-context",
  "messageIfNoResults": "#TODO# There are no security context documents yet. Create a security context document under *Design* → *Document security context*."
{{/report}}

== Dataflow diagram

.Instructions
[%collapsible]
=====
[NOTE]
====
When reviewing this section, check that the following aspects have been documented in the data flow model:

* Processes
* Data stores
* Trust boundaries
* Dataflows, including all interfaces
* Interacting external entities

You can evaluate whether the DFD describes the system with sufficient detail by trying to tell stories of a component's behavior. If the stories contain entities that are not in the model, then the DFD needs updating.

====
=====

== Context diagram

{{#graph}}
  "model": "secdeva/graphModels/dataflow",
  "view": "secdeva/graphViews/context"
{{/graph}}

== Detailed diagram

{{#graph}}
  "model": "secdeva/graphModels/dataflow",
  "view": "secdeva/graphViews/allEntities"
{{/graph}}

== Create a top-level element

Trust boundary:: A trust boundary is a boundary between different trust zone levels.

{{#createCards}}
    "buttonLabel": "Create a trust boundary",
    "template": "secdeva/templates/trustBoundary2"
{{/createCards}}

External entity:: An external entity is a source from which information flows into the system, or a recipients of information leaving the system

{{#createCards}}
  "buttonLabel": "Create an external entity",
  "template": "secdeva/templates/external2"
{{/createCards}}

Person:: A person is a user, an administrator or another human stakeholder. A special case of an external entity.

{{#createCards}}
  "buttonLabel": "Create a person",
  "template": "secdeva/templates/person2"
{{/createCards}}

Process:: A process represents an activity that the system carries out.

{{#createCards}}
  "buttonLabel": "Create a process",
  "template": "secdeva/templates/process2"
{{/createCards}}

Data store:: A data store stores information. For example, a database or a file.

{{#createCards}}
  "buttonLabel": "Create a data store",
  "template": "secdeva/templates/dataStore2"
{{/createCards}}

== 3rd party technologies

.Instructions
[%collapsible]
=====
[NOTE]
====
When reviewing this section, check that technologies that are developed by a 3rd party and linked into the product are listed. That may include

* Applications
* Command line tools
* Libraries
* Drivers
====
=====

Major 3rd party technologies are documented as part of the threat model or directly in {{#report}}"name": "xref", "identifier": "secdeva_register_technology-assessments"{{/report}}:

{{#report}}
  "name": "secdeva/reports/projectTechnologies"
{{/report}}

== Interfaces and physical connections

{{#report}}
  "name": "secdeva/reports/modelInterfaces"
{{/report}}

== Potential attack vectors and attack surface

.Instructions
[%collapsible]
=====
[NOTE]
====
An attack vector is a _route_ or _means_ by which an attacker can attack the system. Examples of attack vectors include

* Accessing the hardware
* Network interface or open protocol port
* User interface
* Query and search function
* Admin interface
* Email or email attachment
* Instant message
* Technology that may be vulnerable to malicious code such as viruses
* Software update
* Weak access control lists
* Login authentication entry points
* Services running with elevated privileges
* Application Programming Interfaces (APIs)

When reviewing this section, ensure that the known potential attack vectors are listed.

Attack surface: The attack surface of a system or a component is the sum of the different points (the "attack vectors") where an unauthorized user (the "attacker") can try to enter data to or extract data from the system or component.

You can use this list of attack vectors to understand the attack surface of the product
====
=====

{{#report}}
  "name": "secdeva/reports/createAttackVector"
{{/report}}

== Identified risks and security issues

.Instructions
[%collapsible]
=====
[NOTE]
====
When reviewing the lists of identified risks and security issues, check that

* Threat modelling was performed in an acceptable level of detail, taking into account possible impacts of cybersecurity risks to the health and safety of users
* According to your best current understanding, all relevant findings have been listed
* The identified risks and security issues have been processed and treatment plans have been documented
* The planned treatment minimise cybersecurity risks, prevent cybersecurity incidents and minimize the impacts of such incidents.

Note that implementing the treatment plan is not part of threat model review.
====
=====

{{#report}}
  "name": "secdeva/reports/threatModelFindings"
{{/report}}

== Threat model reviews

{{#createCards}}
    "template": "base/templates/reviewTask",
    "buttonLabel": "Add a new review task"
{{/createCards}}

{{#report}}
  "name": "base/reports/childrenTable",
  "cardType": "base/cardTypes/reviewTask"
{{/report}}