.View diagram
[%collapsible]
====
{{#graph}}
  "model": "secdeva/graphModels/processDiagram",
  "view": "secdeva/graphViews/processTask"
{{/graph}}
====

APIs, protocols, physical connections, and other interfaces are typically a significant attack vector. Documenting the interfaces according to the interface specification template ensures that secure design principles have been applied when designing the interface.

Examples of interfaces include

* Service interfaces
* Application Programmer's Interfaces (API)
* Communication protocols and links implemented by the development project
* Physical interfaces and ports
* Media ports such as SD card slots
* Wireless connections

== How to decide if this control is required

This control is applicable, if the system includes or implements interfaces and targets at industry standard compliance.

Documenting an interface in the threat model with a separate interface card is required for all exposed interfaces, for which the development project is responsible. This includes

* External interfaces, where the interface may be used by external entities that are not part of the system
* Internal interfaces, which are exposed to other components or devices

== How to implement

1. Document interfaces as part of the threat model. Create separate interface cards and route relevant data flows to the interfaces.
2. Conduct a review of interfaces to ensure that all relevant relevant have been identified.

{{#report}}
  "name": "secdeva/reports/createReview",
  "template": "secdeva/templates/reviewOfInterfaces",
  "buttonLabel": "Create a review of interfaces",
  "phase": "secdeva_phase_design"
{{/report}}

== Assessment

{{#report}}
  "name": "secdeva/reports/internalControlAssessment"
{{/report}}

== References

* IEC 62443-4-1 SD-1
