Cryptography is commonly used for protecting the confidentiality or the integrity of information. When cryptography is used, it must be used properly and effectively, using appropriate algorithms and standards.

Cryptographic keys must be managed properly. This includes creation, exchange, storage, access control and other protection, renewal, revokation, and deletion of keys.

The use of specific algorithms, key lengths, and key management arrangements must be justified by referring to applicable standards or industry best practices.

Whenever human actions are required, the roles and responsibilities for implementing cryptographic controls must be defined.

== How to decide if this control is required

This secure development task is applicable if the project uses cryptography.

== How to implement

Document the use of cryptography and follow the instructions in the template.

{{#report}}
  "name": "secdeva/reports/createDocument",
  "template": "secdeva/templates/useOfCryptography",
  "buttonLabel": "Create a document about the use of cryptography",
  "phase": "secdeva_phase_design"
{{/report}}

== Assessment

{{#report}}
  "name": "secdeva/reports/internalControlAssessment"
{{/report}}

== References

* IEC 62443 4-2 CR 4.3
* IEC 62443 3-3 SR 4.3
* ISO 27001 A8.24
* EU CRA Annex I (2) (3)
* EU CRA Annex I (1) (2) (e)
* EU CRA Annex I (1) (2) (f)