== Source

EU CRA Annex I (1) (2) (j) :: On the basis of the cybersecurity risk assessment referred to in Article 13(2) and where applicable, products with digital elements shall: (j) be designed, developed and produced to limit attack surfaces, including external interfaces;

== Requirement description

#TODO: Edit this as applicable and add any product-specific considerations#

This requirement is implemented by the linked secure development tasks: attack surface is documented and analysed technically.

The product must also support appropriate hardening mechanisms:

* The default configuration shall limit or disable all non-essential features  such as  interfaces, connections, network ports, running services, features, privileges, any APIs, protocols and other entry points  that are not strictly required for performing the tasks that the product is expected to do
* Hardening must consider all applicable layers of the technology stack, such as network devices, operating systems, middleware components, applications
* If required by a risk assessment, a physical product should include tamper-resistant features
