== Source

EU CRA Article 13(19) :: Manufacturers shall ensure that the end date of the support period referred to in paragraph 8, including at least the month and the year, is clearly and understandably specified at the time of purchase in an easily accessible manner and, where applicable, on the product with digital elements, its packaging or by digital means.
Where technically feasible in light of the nature of the product with digital elements, manufacturers shall display a notification to users informing them that their product with digital elements has reached the end of its support period.

== Requirement description

#TODO: Edit this as applicable and add any product-specific considerations#

Include the end date of the support period in the product, its packing or by digital means
If applicable, implement a notification to users informing them that their product is about to  the end of its support period, and a notification that their product has reached the end of its support period.