.View diagram
[%collapsible]
====
{{#graph}}
  "model": "secdeva/graphModels/processDiagram",
  "view": "secdeva/graphViews/processTask"
{{/graph}}
====

Assigning persons to their security-related roles is done to ensure that the responsibilities get done and that people are aware of their responsibilities. Documenting the roles is also useful when planning the security trainings.

== How to decide if this control is required

This control is always required, because persons need to be assigned to roles to execute the secure development processes.

== How to implement this task

Create and edit role assignments and follow the instructions in the template.

{{#report}}
  "name": "secdeva/reports/createReview",
  "template": "secdeva/templates/roleAssignments",
  "buttonLabel": "Create roles assignments",
  "phase": "secdeva_phase_foundation"
{{/report}}

== Assessment

{{#report}}
  "name": "secdeva/reports/internalControlAssessment"
{{/report}}

== References

* IEC 62443-4-1 SM-2
* IEC 62443-4-1 SVV-5
* ISO 27001 A5.2
* EU CRA Annex I (1) (1)
