{{#graph}}
  "model": "secdeva/graphModels/dataflow",
  "view": "secdeva/graphViews/entity"
{{/graph}}

== Composite elements

[TIP]
====
To add a dataflow to or from this data store, click the link symbol in the top level tool bar. Optionally, if you want to model interfaces as well, you can create an interface and link any incoming dataflows to the interface.
====

{{#createCards}}
  "buttonLabel": "Create an interface",
  "template": "secdeva/templates/interface2"
{{/createCards}}

{{#createCards}}
  "buttonLabel": "Create a physical port or connection",
  "template": "secdeva/templates/physicalConnection"
{{/createCards}}

{{#createCards}}
    "buttonLabel": "Create a trust boundary",
    "template": "secdeva/templates/trustBoundary2"
{{/createCards}}

{{#createCards}}
  "buttonLabel": "Create an external entity",
  "template": "secdeva/templates/external2"
{{/createCards}}

{{#createCards}}
  "buttonLabel": "Create a person",
  "template": "secdeva/templates/person2"
{{/createCards}}

{{#createCards}}
  "buttonLabel": "Create a process",
  "template": "secdeva/templates/process2"
{{/createCards}}

{{#createCards}}
  "buttonLabel": "Create a data store",
  "template": "secdeva/templates/dataStore2"
{{/createCards}}

== Interfaces and physical connections

{{#report}}
  "name": "secdeva/reports/entityInterfaces"
{{/report}}

== Related risks

{{#report}}
  "name": "secdeva/reports/createRisk"
{{/report}}

== Related security issues

{{#report}}
  "name": "secdeva/reports/createSecurityIssue"
{{/report}}

== Related security requirements

{{#report}}
  "name": "secdeva/reports/createSecurityRequirement"
{{/report}}

== Related technology assessments

{{#report}}
  "name": "secdeva/reports/createTechnologyAssessment"
{{/report}}

== Related decisions

{{#report}}
  "name": "secdeva/reports/createDecision"
{{/report}}

== Related design specifications

{{#report}}
  "name": "secdeva/reports/createDesignSpecification"
{{/report}}